package pl.com.sobsoft.mongo.training;

import java.util.List;

import static java.util.Arrays.asList;
import static java.util.Collections.unmodifiableList;

public class Data {

    public static final List<String> LAST_NAMES = unmodifiableList(asList("Kowalski", "Nowak", "Ray", "Austin", "Richards", "Boyd", "Sanders", "Castillo", "Wagner", "Morgan", "Williamson", "Elliott", "Jacobs", "Jordan", "Simpson", "Harris", "Harper", "Myers", "Freeman", "Mccoy", "Cooper", "Ferguson", "Morrison", "Jackson", "Perry", "Campbell", "Payne", "Dean", "Little", "Carpenter", "Riley", "Lynch", "Young", "White", "Ryan", "Ford", "Pierce", "Howard", "George", "Nelson", "Berry", "Spencer", "Sullivan", "Bell", "Bishop", "Cox", "Palmer", "Garrett", "Graham", "Bowman", "Moore", "Hansen", "Weaver", "Jenkins", "Garcia", "Larson", "Williams", "Hamilton", "Alvarez", "Ramirez", "Lee", "Franklin", "Rivera", "Snyder", "Hunter", "Hawkins", "Allen", "Moreno", "Meyer", "Hill", "Murray", "Washington", "Peters", "Banks", "Cunningham", "Reynolds", "Lawrence", "Martin", "Carroll", "Dixon", "Duncan", "Scott", "Greene", "Hanson", "Collins", "Harrison", "Long", "Sims", "Holmes", "Brown", "Wright", "Warren", "Stanley", "Clark", "Ramos", "Wood", "Stevens", "Barnes", "Oliver", "Ruiz", "Olson", "Green", "Hayes", "Kelley", "Cole", "Montgomery", "Mason", "Robertson", "Cook", "Armstrong", "Butler", "Fowler", "Kelly", "Richardson", "Day", "Webb", "Romero", "Ellis", "Medina", "Murphy", "Marshall", "Arnold", "Woods", "Rodriguez", "Burns", "Gomez", "Garza", "Porter", "Bailey", "Gordon", "Lawson", "Lewis", "Turner", "Coleman", "Fernandez", "Black", "Carter", "Morales", "Simmons", "Bryant", "Burke", "Parker", "Hudson", "Nichols", "Fisher", "Wheeler", "Hicks", "Hall", "Mendoza", "Henderson", "Watson", "Stone", "Bennett", "Knight", "Gutierrez", "Brooks", "Taylor", "Fox", "Miller", "Tucker", "Lopez", "Alexander", "Peterson", "Stewart", "Welch", "Henry", "Rice", "Grant", "Robinson", "Perkins", "Gonzales", "Johnston", "Gonzalez", "Hart", "Rogers", "Gilbert", "Rose", "Shaw", "Nguyen", "James", "Adams", "Stephens", "Andrews", "Owens", "Vasquez", "Fuller", "Davis", "Chavez", "Morris", "Torres", "Walker", "Patterson", "Price", "Powell", "Wells", "Burton", "West", "Wilson", "Anderson", "Crawford", "Sanchez", "Dunn", "Reed", "Mcdonald", "Chapman", "Lane", "Flores", "Russell", "Jones", "Baker", "Mitchell", "Thomas", "Daniels", "Hughes", "Hernandez", "Reid", "Thompson", "Gray", "Schmidt", "Kim", "Ward", "Gardner", "Phillips", "Kennedy", "Perez", "Gibson", "Foster", "Willis", "Harvey", "Reyes", "Carr", "Smith", "Watkins", "Howell", "Ortiz", "Cruz", "Edwards", "Evans", "Martinez", "Hunt", "King", "Roberts", "Matthews", "Wallace", "Fields", "Diaz", "Bradley", "Griffin"));

    public static final List<String> FIRST_NAMES = unmodifiableList(asList("Louise", "Michael", "Cynthia", "Daniel", "Kevin", "Paul", "Nicole", "Paula", "Joan", "Marilyn", "Samuel", "Pamela", "Ernest", "Denise", "Janet", "Benjamin", "Keith", "Teresa", "Gregory", "Edward", "Larry", "Diana", "Gary", "Brandon", "Ryan", "Diane", "Carlos", "John", "Howard", "George", "Shirley", "Elizabeth", "Virginia", "Clarence", "Mildred", "Richard", "Theresa", "Annie", "Jimmy", "Betty", "Julia", "Julie", "Angela", "Charles", "Amy", "Craig", "Roy", "Ann", "Rebecca", "Ruby", "Tammy", "Christopher", "Kimberly", "Emily", "Evelyn", "Bonnie", "Lois", "Joseph", "Sean", "Sharon", "Aaron", "Sarah", "Jose", "Andrea", "Lawrence", "Martin", "Scott", "Jennifer", "Arthur", "Patricia", "Martha", "Harry", "Andrew", "Fred", "Wanda", "Cheryl", "Jerry", "Dennis", "Mark", "Irene", "Linda", "Mary", "Jean", "Jeremy", "Stephen", "Sandra", "Michelle", "Gerald", "Carolyn", "Lori", "Carol", "Jonathan", "Kathleen", "Kelly", "Bobby", "Gloria", "Beverly", "Robert", "Joe", "Raymond", "Phyllis", "Kathryn", "Victor", "Jack", "Anthony", "Laura", "Helen", "Katherine", "Phillip", "Ruth", "Brian", "Wayne", "Christine", "Brenda", "Randy", "Ronald", "Norma", "Todd", "Christina", "Jacqueline", "Lisa", "Kenneth", "Jason", "Frances", "Shawn", "Johnny", "Henry", "Lillian", "Douglas", "Sara", "Robin", "Judith", "Rose", "Antonio", "Margaret", "James", "Harold", "Jane", "Ashley", "Peter", "Frank", "Chris", "Albert", "Heather", "Alice", "Alan", "Nicholas", "David", "Philip", "Donna", "Ralph", "Joshua", "Catherine", "Russell", "Matthew", "Debra", "Dorothy", "Thomas", "Barbara", "Eric", "Jesse", "William", "Amanda", "Marie", "Maria", "Timothy", "Terry", "Nancy", "Susan", "Anne", "Jessica", "Anna", "Willie", "Billy", "Janice", "Bruce", "Juan", "Kathy", "Melissa", "Stephanie", "Carl", "Karen", "Steven", "Tina", "Joyce", "Roger", "Judy", "Doris", "Steve", "Adam", "Deborah", "Eugene", "Louis", "Donald", "Earl", "Justin", "Jeffrey", "Walter", "Rachel"));

    public static final List<String> FIRST_NAMES_FEMALE = unmodifiableList(asList("Louise", "Cynthia", "Nicole", "Paula", "Joan", "Marilyn", "Pamela", "Denise", "Janet", "Teresa", "Diana", "Diane", "Shirley", "Elizabeth", "Virginia", "Mildred", "Theresa", "Annie", "Betty", "Julia", "Julie", "Angela", "Amy", "Ann", "Rebecca", "Ruby", "Tammy", "Kimberly", "Emily", "Evelyn", "Bonnie", "Lois", "Sharon", "Sarah", "Andrea", "Jennifer", "Patricia", "Martha", "Wanda", "Cheryl", "Irene", "Linda", "Mary", "Jean", "Sandra", "Michelle", "Carolyn", "Lori", "Carol", "Kathleen", "Kelly", "Beverly", "Gloria", "Phyllis", "Kathryn", "Laura", "Helen", "Katherine", "Ruth", "Christine", "Brenda", "Norma", "Christina", "Jacqueline", "Lisa", "Frances", "Lillian", "Sara", "Robin", "Judith", "Rose", "Margaret", "Jane", "Ashley", "Heather", "Alice", "Donna", "Catherine", "Debra", "Dorothy", "Barbara", "Amanda", "Marie", "Maria", "Nancy", "Susan", "Anne", "Jessica", "Anna", "Janice", "Kathy", "Melissa", "Stephanie", "Karen", "Tina", "Joyce", "Judy", "Doris", "Deborah", "Rachel"));

    public static final List<String> FIRST_NAMES_MALE = unmodifiableList(asList("Michael", "Daniel", "Kevin", "Paul", "Samuel", "Ernest", "Benjamin", "Keith", "Gregory", "Edward", "Larry", "Gary", "Brandon", "Ryan", "Carlos", "John", "Howard", "George", "Clarence", "Richard", "Jimmy", "Charles", "Craig", "Roy", "Christopher", "Joseph", "Sean", "Aaron", "Jose", "Lawrence", "Martin", "Scott", "Arthur", "Harry", "Andrew", "Fred", "Jerry", "Dennis", "Mark", "Jeremy", "Stephen", "Gerald", "Jonathan", "Bobby", "Robert", "Joe", "Raymond", "Victor", "Jack", "Anthony", "Patrick", "Phillip", "Brian", "Wayne", "Randy", "Ronald", "Todd", "Kenneth", "Jason", "Shawn", "Johnny", "Henry", "Douglas", "Antonio", "James", "Harold", "Peter", "Frank", "Chris", "Albert", "Alan", "Nicholas", "David", "Philip", "Ralph", "Marek", "Joshua", "Russell", "Matthew", "Thomas", "Eric", "Jesse", "William", "Timothy", "Terry", "Billy", "Willie", "Bruce", "Juan", "Carl", "Steven", "Roger", "Steve", "Adam", "Eugene", "Louis", "Donald", "Earl", "Justin", "Jeffrey", "Walter"));

    public static final List<String> ACCOUNT_TYPES = unmodifiableList(asList("savings", "investment", "checking", "401k"));

    public static final List<String> CURRENCIES = unmodifiableList(asList("USD", "YEN", "PLN", "PHP", "IDR", "RUB", "CZK", "HRK"));

    public static final List<String> GENDER = unmodifiableList(asList("male", "female"));


}
